import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(currentFile), "../..");
const sourcePath = path.join(root, "data/translation-quiz/questions.json");
const outputPath = path.join(root, "miniprogram/data/questions.js");

const source = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const output = [
  "// Generated by miniprogram/scripts/sync_questions.mjs.",
  "// Do not edit this file directly.",
  `module.exports = ${JSON.stringify(source, null, 2)};`,
  ""
].join("\n");

fs.writeFileSync(outputPath, output, "utf8");

const statusCounts = source.questions.reduce((counts, question) => {
  counts[question.quality.status] = (counts[question.quality.status] || 0) + 1;
  return counts;
}, {});

console.log(JSON.stringify({ questions: source.questions.length, statusCounts }, null, 2));
